# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/EEM464/2014_4_zynq_labs/Hardware_test_SoC_Project_Barret_Reduction/Hardware_test_SoC_Project_Barret_Reduction.cache/wt [current_project]
set_property parent.project_path C:/EEM464/2014_4_zynq_labs/Hardware_test_SoC_Project_Barret_Reduction/Hardware_test_SoC_Project_Barret_Reduction.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo c:/EEM464/2014_4_zynq_labs/Hardware_test_SoC_Project_Barret_Reduction/Hardware_test_SoC_Project_Barret_Reduction.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/lenovo/Desktop/oled filelar/ascii_rom.vhd}
  C:/EEM464/2014_4_zynq_labs/Hardware_test_SoC_Project_Barret_Reduction/Hardware_test_SoC_Project_Barret_Reduction.srcs/sources_1/new/barret_reduction.vhd
  {C:/Users/lenovo/Desktop/oled filelar/bcd_ascii.vhd}
  {C:/Users/lenovo/Desktop/oled filelar/debounce.vhd}
  {C:/Users/lenovo/Desktop/oled filelar/delay.vhd}
  {C:/Users/lenovo/Desktop/oled filelar/oled_drive.vhd}
  {C:/Users/lenovo/Desktop/oled filelar/oled_init.vhd}
  {C:/Users/lenovo/Desktop/oled filelar/spi_ctrl.vhd}
  {C:/Users/lenovo/Desktop/oled filelar/mod_mul_with_oled.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/lenovo/Desktop/oled filelar/constraints.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/lenovo/Desktop/oled filelar/constraints.xdc}}]


synth_design -top mod_mul_with_oled -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mod_mul_with_oled.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mod_mul_with_oled_utilization_synth.rpt -pb mod_mul_with_oled_utilization_synth.pb"
