webtalk_init -webtalk_dir C:/Users/lenovo/Desktop/EEM464_Vivado_Projeler/SoC_Barret_Reduction_Deneme/SoC_Barret_Reduction_Deneme.sim/sim_1/behav/xsim/xsim.dir/barret_test_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Apr 24 19:06:04 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "48980b89-2c31-4188-947f-c6108760931c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "9751ad25069e4a18bb9172e74f5ce4bf" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2400 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7164_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1887952964 -regid "" -xml C:/Users/lenovo/Desktop/EEM464_Vivado_Projeler/SoC_Barret_Reduction_Deneme/SoC_Barret_Reduction_Deneme.sim/sim_1/behav/xsim/xsim.dir/barret_test_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/lenovo/Desktop/EEM464_Vivado_Projeler/SoC_Barret_Reduction_Deneme/SoC_Barret_Reduction_Deneme.sim/sim_1/behav/xsim/xsim.dir/barret_test_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/lenovo/Desktop/EEM464_Vivado_Projeler/SoC_Barret_Reduction_Deneme/SoC_Barret_Reduction_Deneme.sim/sim_1/behav/xsim/xsim.dir/barret_test_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
